apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: spawner
  annotations:
    homeroom/title: "AsciiDoc Sample"
    homeroom/description: "A sample workshop using AsciiDoc."
spec:
  rules:
  - http:
      paths:
      - host: "lab-asciidoc-sample.${CLUSTER_SUBDOMAIN}"
        path: "/"
        backend:
          serviceName: spawner
          servicePort: 8080
